### ISSUE TITLE
How to connect to mainnet?

### ISSUE THREAD

**Issue by danielimkk** [DNAProject/Documentation#7]
`/dna/dnaNode --enable-consensus --rest --password password --config /dna/config.json --wallet /dna/Chain/wallet.dat;` I'm connecting to mainnet using the above command. But node gets stuck on `CurrentBlockHeight = 0` But seed list looks like this:
 ` "SeedList": [
    "127.0.0.1:20338",
    "127.0.0.01:20438",
    "127.0.0.01:20538",
    "127.0.0.01:20638"
  ],` 
Is there any doc that describes how to connect to mainnet? I don't know Chinese, so I couldn't clearly understand everything mentioned. So if there is a page describing how to run a node and connect to mainnet, please share a link with me

**Comment by Honglei-Cong** [comment]
There's  no mainnet.
Please refer to DNA/README.md, to setup your own network.

**Comment by danielimkk** [comment]
So there is no network to connect to? Only private ones?

**Comment by Honglei-Cong** [comment]
Right.  There's no public net.

**Comment by Honglei-Cong** [comment]
It'll be also great if you like to setup one public net :)

**Comment by danielimkk** [comment]
Sure, got it:) Thanks for clearing it out
